/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main$package$ */

#ifndef _Included_main_00024package_00024
#define _Included_main_00024package_00024
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      main$package$
 * Method:     answer
 * Signature:  ()I
 */
JNIEXPORT jint JNICALL Java_main_00024package_00024_answer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
